# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TG9OeLDXE2GQbkpO0msM09Lq5z1fqzR6
"""

!pip install PyPDF2

from PyPDF2 import PdfWriter, PdfReader
from getpass import getpass

pdfwriter = PdfWriter()
pdf = PdfReader(input('Введите название пдф-файла: '))

for page in range(len(pdf.pages)):
  pdfwriter.add_page(pdf.pages[page])

password = getpass(prompt = 'Введите пароль: ')
pdfwriter.encrypt(password)

with open('protected.pdf', 'wb') as file:
  pdfwriter.write(file)